### PR TITLE
Moves via away from pad

### PR DESCRIPTION
**Pull request by spuder**
Fixes issue #8

### CODE REVIEW

**Comment by spuder** [comment]
Before

screen shot 2015-12-09 at 10 32 28 pm

After

Notice that I moved the 1 pad and the 2 vias so they aren't so close together. 

screen shot 2015-12-12 at 5 18 54 pm

screen shot 2015-12-12 at 5 19 46 pm

screen shot 2015-12-12 at 5 19 02 pm

Still pretty new at KiCad but it passes the Diagnostic Rules check. 
I don't know if it matters, but this was done with a 10mils grid instead of a 50 mils grid

**Comment by mondalaci** [comment]
Thanks for the fix! I'll have to set up visual diffing for KiCad to be able to check contributions because upon regenerating the netlist thousands of lines get changed, just like in this pull request. Luckily, there are some tutorials on the subject. Please let me get back to this a little bit later.

**Comment by spuder** [comment]
From my research, you can run the following script. 

https://github.com/madworm/KiCad-Stuff/tree/master/scripts/visual-diffs_on_gerber-files

https://www.youtube.com/watch?v=diMIU0YYB9w

I can't quite get it to work on OSX yet. It may be possible to use travis-ci to automatically generate a diff file and save it as an artifact. 

https://blog.travis-ci.com/2012-12-18-travis-artifacts/

**Comment by spuder** [comment]
Here is a script that generates a gerber in kicad

http://www.evilmadscientist.com/2011/improving-open-source-hardware-visual-diffs/

If this script could be modified to output to a .pdf instead of a gerber file, then this blog has instructions on how to generate a diff file. 

http://www.evilmadscientist.com/2011/improving-open-source-hardware-visual-diffs/

I spent a few hours on this without progress. I'll pick this back up soon.

**Comment by spuder** [comment]
Closing. In writing the scripts to create the visual diffs, I noticed a problem. The pad takes away from the thickness of the path. Will open a new pull request when fixed. 

screen shot 2015-12-18 at 5 01 54 pm

**Pull request closed without merging**
